baseURL = 'https://kr.lusw.dev/'
languageCode = 'zh-Hant'
title = '우연히 유년잉'
contentDir = 'content'
enableEmoji = true
enableRobotsTXT = true

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[services]
    [services.googleAnalytics]
        id = 'G-GCX6LZQLR2'

[params]
    # Google Fonts
    google_fonts = [
        ["Lato", "300, 400, 600, 700"],
        ["JetBrains Mono", "300, 400, 600, 700"],
        ["Noto Sans KR", "300, 400, 600, 700"],
        ["Noto Sans TC", "300, 400, 600, 700"],
        ["Noto Serif KR", "300, 400, 600, 700"],
        ["Noto Serif TC"," 300, 400, 600, 700"],
    ]

    sans_serif_font = "Noto Serif TC, Noto Serif KR"     # Default is System font
    secondary_font  = "Lato, Noto Sans TC, Noto Sans KR"     # Default is System font
    mono_font       = "JetBrains Mono" # Default is System font

    [params.social]
        instagram = "yunyeoning"
        threads = "yunyeoning"
        # twitter = "yunyeoning"
        youtube = "@yunyeoning"

    [params.footer]
        copyright = "All photos are property of their respective owners. Lyric translation by &copy; :YEAR: LuSkywalker"
        version   = true

    [params.docs]
        darkMode = true
        sidebarIcons = true
        titleIcon = true
        backToTop = true
        logoLinkURL = "/docs/"
        pathName = "docs"
        themeColor = "jinahon"
        descriptions = true
        toc = true
        tocMobile = true
        scrollSpy = true