baseURL = 'https://yholics.lusw.dev/'
languageCode = 'en-us'
title = 'Y.HOLICS 台灣粉絲站'
contentDir = 'content'
enableEmoji = true

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    # Google Fonts
    google_fonts = [
        ["Lato", "300, 400, 600, 700"],
        ["JetBrains Mono", "300, 400, 600, 700"],
        ["Noto Sans KR", "300, 400, 600, 700"],
        ["Noto Sans TC", "300, 400, 600, 700"],
        ["Noto Serif KR", "300, 400, 600, 700"],
        ["Noto Serif TC"," 300, 400, 600, 700"],
    ]

    sans_serif_font = "Lato, Noto Sans TC, Noto Sans KR"     # Default is System font
    secondary_font  = "Lato, Noto Sans TC, Noto Sans KR"     # Default is System font
    mono_font       = "JetBrains Mono" # Default is System font

    [params.footer]
        copyright = "This website is not affiliated with [C9 Ent](https://www.c9ent.co.kr/). All photos are property of their respective owners &copy; :YEAR: LuSkywalker"
        version   = true

    [params.docs]
        darkMode = true
        sidebarIcons = true
        titleIcon = true
        backToTop = true
        logoLinkURL = "/docs/"
        pathName = "docs"
        themeColor = "yholics"
        descriptions = true